name: Multiverse-NetherPortals
main: org.mvplugins.multiverse.netherportals.MultiverseNetherPortals
authors: ['Rigby', 'fernferret', 'benwoo1110']
version: ${version}
api-version: 1.13
depend: ['Multiverse-Core']
softdepend: ['Multiverse-Portals']
